-- SELECT QUERIES
SELECT * FROM TASKS;
SELECT * FROM USERS;
SELECT * FROM DBLOGGER;
SELECT * FROM USERS USR INNER JOIN TASKS TSK ON USR.USER_ID = TSK.USER_ID;


-- INSERT/UPDATE QUERIES
INSERT INTO USERS(USERNAME, USER_EMAIL) VALUES('YASH', 'YASH@GMAIL.COM');



-- TRUNCATE/DROP/DELETE QUERIES
TRUNCATE TABLE USERS;
TRUNCATE TABLE TASKS;
TRUNCATE TABLE DBLOGGER;



-- ALTER QUERIES
ALTER TABLE PUBLIC.TASKS DROP COLUMN USER_ID;
ALTER TABLE PUBLIC.TASKS ADD COLUMN USER_ID CHARACTER VARYING(255);
ALTER TABLE PUBLIC.TASKS ADD CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE;
ALTER TABLE DBLOGGER DROP COLUMN STACK_TRACE;
ALTER TABLE DBLOGGER ADD COLUMN STACK_TRACE TEXT;
ALTER TABLE USERS DROP COLUMN CREATED_AT;
ALTER TABLE USERS ADD COLUMN CREATED_AT TIMESTAMP;
ALTER TABLE TASKS DROP COLUMN TASK_CREATED_AT
ALTER TABLE TASKS ADD COLUMN TASK_CREATED_AT TIMESTAMP;
ALTER TABLE TASKS DROP CONSTRAINT FK_USER_ID;
ALTER TABLE USERS DROP COLUMN TASKS_ASSIGNED;






































